### PR TITLE
Fix bug: Messaging based scenario not works as expected.

### PR DESCRIPTION
**Pull request by backwind1233**
Fix bug: when cloud stream, spring integration, and servicebus are selected
1. Dependency `spring-cloud-azure-dependencies` is missing which should not. 
2. Only `spring-cloud-azure-stream-binder-servicebus` or `spring-cloud-azure-starter-integration-servicebus` is imported.
    - The expected behavior is both `spring-cloud-azure-stream-binder-servicebus` and `spring-cloud-azure-starter-integration-servicebus` should be imported.

### CODE REVIEW

**Comment by saragluna** [comment]
@stliu should we merge this?

**Comment by backwind1233** [comment]
@stliu @saragluna I think it's good opportunity to let @fangjian0423 review this PR, and learn how [azure-spring-initializr](https://github.com/Azure/azure-spring-initializr) works.

**Comment by fangjian0423** [comment]
For this point:

> Only spring-cloud-azure-stream-binder-servicebus or spring-cloud-azure-starter-integration-servicebus is imported.

After testing, I found spring-cloud-azure-stream-binder-servicebus and spring-cloud-azure-starter-integration-servicebus are all imported.

image

@backwind1233 do you think this is right?

**Comment by backwind1233** [comment]
> 2. spring-cloud-azure-stream-binder-servicebus

@fangjian0423 
Could you tell me how you reproduce this issue, what's the order you add dependencies, what's the branch you are using?

I tested it locally with the main branch,
image

**Review by fangjian0423 — APPROVED** [review]
LGTM

**Pull request merged**
